name: mno_shared
description: Contains the definitions of the custom types (model) used across the Readium-2 Dart projects.
version: 0.1.3
homepage: https://github.com/Mantano/mno_shared_dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  archive: ^3.1.8
  collection: ^1.15.0
  crypto: ^3.0.1
  dartx: ^1.0.0
  dfunc: ^0.7.2
  equatable: ^2.0.3
  fimber: ^0.6.4
  http: ^0.13.4
  image: ^3.1.1
  intl: ^0.17.0
  meta: ^1.7.0
  path: ^1.8.0
  universal_io: ^2.0.4
  xml: ^5.3.1
  mno_commons:
    path: ../commons

dev_dependencies:
  image_compare: ^1.1.2
  lints: ^1.0.1
  test: ^1.20.1
