name: mno_navigator
description: This package provides a DART LCP layer (native libraries not provided).
version: 0.1.0
homepage: https://github.com/Mantano/mno_lcp_dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.2
  dartx: ^1.0.0
  dfunc: ^0.7.2
  equatable: ^2.0.3
  fimber: ^0.6.4
  flutter_bloc: ^8.0.1
  flutter_inappwebview: ^5.3.2
  photo_view: ^0.13.0
  preload_page_view: ^0.1.6
  universal_io: ^2.0.4
  webview_flutter: ^3.0.0
  webview_flutter_web: ^0.1.0

  mno_commons:
    path: ../commons
  mno_server:
    path: ../server
  mno_shared:
    path: ../shared
  mno_streamer:
    path: ../streamer

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1

flutter:

  assets:
    - assets/xpub-assets/
    - assets/xpub-shared-js/
    - assets/xpub-js/
    - assets/xpub-js/controllers/
    - assets/xpub-js/model/
    - assets/xpub-js/utils/
